/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPurgeRouteImport } from './routes/api/purge'
import { Route as ApiIntelRouteImport } from './routes/api/intel'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPurgeRoute = ApiPurgeRouteImport.update({
  id: '/api/purge',
  path: '/api/purge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntelRoute = ApiIntelRouteImport.update({
  id: '/api/intel',
  path: '/api/intel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/intel': typeof ApiIntelRoute
  '/api/purge': typeof ApiPurgeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/intel': typeof ApiIntelRoute
  '/api/purge': typeof ApiPurgeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/intel': typeof ApiIntelRoute
  '/api/purge': typeof ApiPurgeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/intel' | '/api/purge'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/intel' | '/api/purge'
  id: '__root__' | '/' | '/api/intel' | '/api/purge'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiIntelRoute: typeof ApiIntelRoute
  ApiPurgeRoute: typeof ApiPurgeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/purge': {
      id: '/api/purge'
      path: '/api/purge'
      fullPath: '/api/purge'
      preLoaderRoute: typeof ApiPurgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/intel': {
      id: '/api/intel'
      path: '/api/intel'
      fullPath: '/api/intel'
      preLoaderRoute: typeof ApiIntelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiIntelRoute: ApiIntelRoute,
  ApiPurgeRoute: ApiPurgeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
